# Site settings
title: Matt Flowers
header-img: assets/img/home-bg.jpg
email: mattmflowers28@gmail.com
copyright_name: Matt Flowers
description: "Just a blog of a developer who has no life but still does not post very often."
baseurl: "/blog"
url: "https://mattflow.github.io"
twitter_username: _flattmo
github_username:  mattflow
# facebook_username:  StartBootstrap
email_username:  mattmflowers28@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
sass:
  style: compressed
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
plugins:
  - jekyll-feed
  - jekyll-paginate